### ISSUE TITLE
[beta][qa] 모바일 > 스타트업 >  정보 영역 > 공개 / 비공개 버튼 크기가 상이한 이슈

### ISSUE THREAD

**Issue by cham-sim** [nextunicorn-inc/nu-packages#72]
Browser : Chrome
Device : Android

현재 오류: 스타트업이 모바일에서 IR자료 공개 여부를 설정할 때 노출되는 공개 / 비공개 버튼의 크기가 상이합니다.
재현 방법:
수정 요청: 피그마와 동일하도록 수정 요청드립니다
페이지 URL:
Figma URL:

![Image](https://user-images.githubusercontent.com/113438910/195813480-80a7cab4-56fa-416c-a7ea-02ba98fde5fb.jpg)

![Image](https://user-images.githubusercontent.com/113438910/196095112-1630341a-de66-4fa1-bf6e-a2af13658882.png)

**Comment by chris-nextunicorn** [comment]
@InSeong-So 아직 요거 처리 안되었나요? 새로운 패키지 받으면 될까요?

**Comment by InSeong-So** [comment]
@chris-nextunicorn 이거 해결은 해서 배포는 되었으나 새로운 패키지 받으면 font-weight 설정하는 `Typography.size`에서 에러가 날 거라 래핑해서 사용하도록 챔과 스티븐에게 이야기 해두었어요!

**Comment by InSeong-So** [comment]
b6edc3ce5a897768e78a00ef1791d82ec67a48ca
